 const var POSINFINITY = 1/0;
 
 const var NUMOFSTRINGS = Globals.NUMOFSTRINGS;
 const var LOWESTNOTE = 52;
 const var HIGHESTNOTE = 97;
 
 const var OPENSTRING6NOTE = 52;
 const var OPENSTRING5NOTE = 57;
 const var OPENSTRING4NOTE = 62;
 const var OPENSTRING3NOTE = 67;;
 const var OPENSTRING2NOTE = 71;
 const var OPENSTRING1NOTE = 76;
 
 const var NO_NOTE = -1;
 
 const var NOTESPERSTRING = 22;
 
 const var OPENSTRINGNONOTE = POSINFINITY;
 
 const var OPENSTRINGNOTES = [OPENSTRING1NOTE, OPENSTRING2NOTE, OPENSTRING3NOTE, OPENSTRING4NOTE, OPENSTRING5NOTE, OPENSTRING6NOTE];
 
 OPENSTRINGNOTES.push(OPENSTRINGNONOTE);